import localFont from "next/font/local";
import "@/styles/globals.css";
import { Inter } from "next/font/google";
import Nav from "@/components/base/Nav";
import Footer from "@/components/base/Footer";
import { Providers } from "@/app/Providers";

const inter = Inter({
  subsets: ["latin"],
  weights: [400, 500, 600, 700],
  variable: "--font-inter",
});

export const metadata = {
  title: "Jardin de Telas",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <Providers>
      <html lang="es">
        <body className="bg-[#EEEDEB]">
          <Nav />
          <main className="min-h-screen $inter.classname">{children}</main>
          <Footer />
        </body>
      </html>
    </Providers>
  );
}
