# Generated by Django 5.1 on 2024-12-02 04:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="rut",
            field=models.CharField(
                max_length=20,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{1,2}\\.\\d{3}\\.\\d{3}-[\\d|kK]{1}$",
                        "Formato de RUT inválido",
                    )
                ],
            ),
        ),
    ]
