# Generated by Django 5.1 on 2024-12-02 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0002_alter_usuario_rut"),
    ]

    operations = [
        migrations.RenameField(
            model_name="direccion",
            old_name="ciudad",
            new_name="comuna",
        ),
    ]
