# Generated by Django 5.1 on 2024-12-02 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0003_rename_ciudad_direccion_comuna"),
    ]

    operations = [
        migrations.AlterField(
            model_name="direccion",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="direccion",
                to="usuarios.usuario",
            ),
        ),
    ]
