# Generated by Django 5.1 on 2024-12-02 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("usuarios", "0004_alter_direccion_usuario"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="direccion",
            name="usuario",
        ),
        migrations.AddField(
            model_name="usuario",
            name="direccion",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="usuarios.direccion",
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="groups",
            field=models.ManyToManyField(
                blank=True, related_name="custom_user_groups", to="auth.group"
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True, related_name="custom_user_permissions", to="auth.permission"
            ),
        ),
    ]
