# Generated by Django 5.1 on 2024-12-02 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0005_remove_direccion_usuario_usuario_direccion_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="direccion",
            name="es_principal",
        ),
    ]
