# Generated by Django 5.1 on 2024-12-05 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0006_remove_direccion_es_principal"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usuario",
            old_name="id_usuario",
            new_name="id",
        ),
    ]
